// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qisjhebviprfeesuqkmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpc2poZWJ2aXByZmVlc3Vxa21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjcxNjksImV4cCI6MjA3MjM0MzE2OX0.uWiaGlj41lCcgjJzfIHOlD34Hd05Arh_jFmdGNW6C7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});